image: ghcr.io/serc-terraform-labs/gitpod-terraform-image:full

vscode:
  extensions:
    - hashicorp.terraform
    - github.vscode-pull-request-github
    - ms-azuretools.vscode-docker
    - amazonwebservices.aws-toolkit-vscode
